// ...existing code from /home/vasuc/workbench/go/extract/config.go...

type ExtractionConfig struct {
	// ...existing fields...
	SplitRules map[string][]string `json:"split_rules"` // procedure name -> columns to split on
}

// ...existing code...
